www/blueprints/control.py
# -*- coding: utf-8 -*-
#
# AMETIST - AMETIST Meteorological Information System
# Copyright (C) 2014  Mikhael Malkov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import calendar
from crochet import TimeoutError
import datetime
import logging
import time
import traceback
from traceback import format_exc
from twisted.internet.defer import CancelledError
from flask import Blueprint, abort, render_template, request,redirect, url_for

from .control_gates import gate_core_control, gate_core_channel, gate_core_inject, gate_ioj_minimum, gate_ioj_hour, gate_ioj_uid
from server.channel import Phase
from www.utils import std_response
from server.thecore import core


__author__ = 'viruzzz-kun'

module = Blueprint('CoreControl', __name__)


@module.context_processor
def core_channel_names():
    return {
        'channels': core.channels.keys(),
        'get_stat': core.get_stat,
        'Phase': Phase,
    }

@module.route('/index.html')
def html_index_redirect():
    return redirect(url_for('.html_index'))


@module.route('/')
def html_index():
    return render_template('core.index.html')


@module.route('/api/core/')
@module.route('/api/core/<command>', methods=['POST'])
def api_core_control(command=None):
    try:
        gate_core_control(command)
    except:
        return std_response(traceback.format_exc())
    return std_response(None)


@module.route('/api/channel/')
@module.route('/api/channel/<channel>/<command>', methods=['POST'])
def api_channel_control(channel, command):
    if channel not in core.channels:
        return abort(404)
    try:
        gate_core_channel(channel, command)
    except:
        return std_response(traceback.format_exc())
    return std_response(None)


@module.route('/api/inject', methods=['POST'])
def api_inject():
    now = time.time()
    logging.debug('%s', request.json)
    j = request.json
    config = {
        'conditions': {
            'beg': now - 3600,
            'end': now,
        },
        'actions': {},
    }
    inputs = j.get('inputs')
    if inputs:
        config['conditions']['origin'] = inputs.split()
    
    ahl = j.get('ahl')
    if ahl:
        config['conditions']['ahl'] = ahl
    
    tags_p = j.get('tags_p')
    tags_m = j.get('tags_m')
    if tags_p or tags_m:
        tp = tags_p.split() if tags_p else []
        tm = tags_m.split() if tags_m else []
        config['conditions']['tags'] = [tp, tm]

    dests_p = j.get('dests_p')
    dests_m = j.get('dests_m')
    if dests_p or dests_m:
        dp = dests_p.split() if dests_p else []
        dm = dests_m.split() if dests_m else []
        config['conditions']['dests'] = [dp, dm]

    destinations = j.get('dests')
    if destinations:
        dests = [name for (name, val) in destinations.items() if val]
        if dests:
            config['actions']['destinations'] = dests

    logging.debug('config = %s', config)

    gate_core_inject(config, core.inject_message)
    return std_response('Started...')


@module.route('/api/ioj/minimum.json')
def api_ioj_minimum():
    return std_response(gate_ioj_minimum())


@module.route('/api/ioj/date/')
@module.route('/api/ioj/date/<the_date>')
def api_ioj_thedate(the_date):
    try:
        d = datetime.datetime.strptime(the_date, '%Y%m%d%H%M')
    except ValueError:
        return abort(402)

    timestamp = calendar.timegm(d.utctimetuple())
    config = {
        'conditions': {
            'beg': timestamp,
            'end': timestamp + 900,
        },
        'actions': {},
    }
    try:
        result = gate_ioj_hour(config)
    except CancelledError or TimeoutError:
        return abort(504)

    ret = std_response(result)
    logging.debug('Finished making response')
    return ret


@module.route('/api/ioj/uid/')
@module.route('/api/ioj/uid/<int:uid>')
def api_ioj_uid(uid):
    try:
        message = gate_ioj_uid(uid)
    except KeyError:
        return abort(404)
    except:
        return format_exc(), 404
    else:
        if message.has_tags('text') or message.no_tags('binary', 'BUFR', 'FAX', 'GRIB'):
            return message.as_string(delimiter='<br/>\n'), 200, [('content-type', 'text/html; encoding=utf-8')]
        elif message.has_tags('binary'):
            message = message.clone()
            message.payload = 'BINARY'
        return message.as_string(delimiter='<br/>\n'), 200, [('content-type', 'text/html; encoding=utf-8')]

@module.route('/api/ioj/uid/<int:uid>/raw')
def api_uij_uid_raw(uid):
    try:
        message = gate_ioj_uid(uid)
    except KeyError:
        return abort(404)
    except:
        return format_exc(), 404
    else:
        return message.as_string(delimiter='\n'), 200, [('content-type', 'application/octet-stream')]

www/blueprints/send.py
# -*- coding: utf-8 -*-
#
# AMETIST - AMETIST Meteorological Information System
# Copyright (C) 2014  Mikhael Malkov
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import crochet
from flask import Blueprint, render_template, request, abort
import shutil
import yaml
from libametist import Message

from server.thecore import core
from ..utils import std_response


__author__ = 'viruzzz-kun'


module = Blueprint('Send', __name__)


@module.route('/index.html')
def html_index():
    return render_template(
        'send.index.html'
    )


@module.route('/api/templates.json')
def api_templates():
    with open('./etc/ametist/message_templates.yaml', 'rt') as f:
        templates = yaml.load(f)
    return std_response([{
        'name': name,
        'data': data,
    } for name, data in templates.iteritems()])


@crochet.run_in_reactor
def gate_send_message(message):
    core.dispatch_message(message, 'xsend')


@module.route('/api/send-wmo-message', methods=['POST'])
def api_send_wmo_message():
    inp = request.json
    if not inp:
        return abort(400)
    addr = inp.get('hms_addr')
    message = Message()
    if addr:
        message['hms_addr'] = addr
        message.format = 'hms'
    else:
        message.format = 'wmo'
    message.payload = inp.get('text')
    message['ahl'] = inp.get('ahl')
    message['timestamp'] = inp.get('timestamp')
    group = inp.get('group')
    if group:
        message['group'] = group
    message.tag('wmo', 'xsend')
    gate_send_message(message)
    return ''


@module.route('/api/save-wmo-template', methods=['POST'])
def api_save_wmo_template():
    inp = request.json
    with open('./etc/ametist/message_templates.yaml', 'rt') as f:
        templates = yaml.safe_load(f)
    templates[inp['name']] = inp['data']
    with open('./etc/ametist/message_templates.yaml.tmp', 'wt') as f:
        yaml.safe_dump(templates, f, indent=2, default_flow_style=False, encoding='utf-8')
    shutil.move('./etc/ametist/message_templates.yaml.tmp', './etc/ametist/message_templates.yaml')
    return std_response([{'name': name, 'data': data, } for name, data in templates.iteritems()])

www/templates/_core.control.html
<div ng-controller="CoreMainCtrl">
    <div class="panel panel-primary">
        <div class="panel-heading">Управление</div>
        <table class="table">
            <thead>
            <tr>
                <th class="col-sm-8">Состояние</th>
                <th class="text-center col-sm-2">Uptime</th>
                <th class="text-center col-sm-3">Ctrl</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-class="{'danger': stats.phase != 2}">
                <td>[[ phase_text[stats.phase] ]] <span ng-if="!stats">Нет связи</span></td>
                <td class="text-center" ng-bind="stats.time_time"></td>
                <td class="text-right">
                    <div class="btn-group">
                        <a class="btn glyphicon btn-success glyphicon-play" href=""
                           ng-if="stats.phase != 2"
                           ng-click="core_command('start')" title="Запустить"></a>
                        <a class="btn glyphicon btn-danger glyphicon-stop" href=""
                           ng-if="stats.phase == 2"
                           ng-click="core_command('stop')" title="Остановить"></a>
                        <a class="btn glyphicon btn-danger glyphicon-flash" href=""
                           ng-if="stats.phase == 2"
                           ng-click="core_command('restart')" title="Перезапустить"></a>
                        <a class="btn glyphicon btn-warning glyphicon-repeat" href=""
                           ng-click="core_command('reload')"
                           title="Перезагрузить таблицу маршрутизации"></a>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
        <table class="table">
            <thead>
            <tr>
                <th>Канал</th>
                <th class="text-center col-sm-1">Rx</th>
                <th class="text-center col-sm-1">Tx</th>
                <th class="text-center col-sm-1">Q</th>
                <th class="text-center col-sm-1">T</th>
                <th class="text-center col-sm-2">Ctrl</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-class="{'warning': stat.queued > 0, 'danger': stat.phase != 2}"
                ng-repeat="(name, stat) in stats.channels">
                <td>
                    [[ name ]] ([[ phase_text[stat.phase] ]]<span ng-if="stat.extState">, [[ stat.extState ]]</span>)
                </td>
                <td class="success text-right" ng-bind="stat.received"></td>
                <td class="success text-right" ng-bind="stat.sent"></td>
                <td class="warning text-right" ng-bind="stat.queued"></td>
                <td class="info text-right" ng-bind="stat.backed"></td>
                <td class="text-right">
                    <div class="btn-group">
                        <a class="btn glyphicon btn-success glyphicon-play"
                           ng-if="stat.phase != 2 && stats.phase == 2"
                           ng-click="channel_command(name, 'start')" title="Запустить"></a>
                        <a class="btn glyphicon btn-danger glyphicon-stop"
                           ng-if="stat.phase == 2"
                           ng-click="channel_command(name, 'stop')" title="Остановить"></a>
                        <a class="btn glyphicon btn-danger glyphicon-flash"
                           ng-if="stats.phase == 2"
                           ng-click="channel_command(name, 'restart')" title="Перезапустить"></a>
                        <a class="btn glyphicon btn-warning glyphicon-ban-circle"
                           ng-click="channel_command(name, 'purge')" title="Очистить очередь"></a>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<script>
    Ametist.controller('CoreMainCtrl', ['$scope', '$http', '$WebSocket', function ($scope, $http, $WebSocket) {
        $scope.aux = aux;
        $scope.stats = null;
        $scope.ws = new $WebSocket('ws://' + location.host + '/{{ app_config.get('ws-path', 'ws') }}/');
        $scope.ws.onOpen(function () {
            $scope.ws.send({
                subscribe: {
                    stats: {}
                }
            });
        });
        $scope.msglog = [];
        $scope.ws.onMessage(function (data) {
            if (data.variant == 'stats') {
                $scope.stats = data.data;
            }
        });
        $scope.ws.onDisconnect(function () {
            $scope.stats = null;
        });
        $scope.ws.connect();

        $scope.core_command = function (command) {
            $http.post('{{ url_for('CoreControl.api_core_control') }}' + command, {})
        };
        $scope.channel_command = function (channel, command) {
            $http.post('{{ url_for('CoreControl.api_channel_control') }}' + channel + '/' + command, {})
        };
        $scope.phase_text = ['Stopped', 'Starting', 'Running', 'Stopping']
    }])
</script>

www/templates/_core.history.html
<div ng-controller="MessageSelectCtrl">
    <div class="panel panel-primary">
        <div class="panel-heading">История</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <button class="btn btn-default dropdown-toggle"
                            ng-click="toggle_conditions_visible()"
                            ng-disabled="_loading">
                        <span ng-if="!_loading">Условия</span><span ng-if="_loading">Загружается...</span>
                        <span class="glyphicon glyphicon-chevron-down"></span>
                    </button>
                    <div class="well" ng-show="conditions_visible"
                         style="display:block; position: absolute; margin-top: 8px; z-index: 1000">
                        <div class="row">
                            <div class="col-sm-8">
                                <datepicker min="min_date" max="max_date" show-weeks="false" ng-model="search_date"></datepicker>
                            </div>
                            <div class="col-sm-4">
                                <timepicker minute-step="15" show-meridian="false" readonly-input="true" ng-model="search_date"></timepicker>
                                <button class="btn btn-success" ng-click="get_data()">Получить</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 text-right">
                    [[ aux.moment(search_date).utc().format('YYYY.MM.DD HH:mm') ]] UTC
                </div>
            </div>
            <div class="row" ng-if="flt_origins.length">
                <div class="col-sm-12">
                    Источник:
                    <span ng-repeat="origin in flt_origins" class="label label-warning tag-label">
                        [[origin]]
                        <span ng-click="aux.removeitem(flt_origins, origin)" class="glyphicon glyphicon-remove tag-remove"></span>
                    </span>
                    <span class="label label-danger tag-label tag-remove" ng-click="flt_origins.splice(0, flt_origins.length)">
                        Очистить <span class="glyphicon glyphicon-remove"></span>
                    </span>
                </div>
            </div>
            <div class="row" ng-if="flt_tags.length">
                <div class="col-sm-12">
                    Теги:
                    <span ng-repeat="tag in flt_tags" class="label label-warning tag-label">
                        [[tag]]
                        <span ng-click="aux.removeitem(flt_tags, tag)" class="glyphicon glyphicon-remove tag-remove"></span>
                    </span>
                    <span class="label label-danger tag-label tag-remove" ng-click="flt_tags.splice(0, flt_tags.length)">
                        Очистить <span class="glyphicon glyphicon-remove"></span>
                    </span>
                </div>
            </div>
            <div class="row" ng-if="flt_dests.length">
                <div class="col-sm-12">
                    Направления:
                    <span ng-repeat="dest in flt_dests" class="label label-warning tag-label">
                        [[dest]]
                        <span ng-click="aux.removeitem(flt_dests, dest)" class="glyphicon glyphicon-remove tag-remove"></span>
                    </span>
                    <span class="label label-danger tag-label tag-remove" ng-click="flt_dests.splice(0, flt_dests.length)">
                        Очистить <span class="glyphicon glyphicon-remove"></span>
                    </span>
                </div>
            </div>
            <div class="text-center">
                <pagination total-items="records_filtered().length" page="current_page" max-size="10"
                            items-per-page="items_per_page" boundary-links="true" ng-show="records"></pagination>
            </div>
        </div>
        <table class="table table-condensed-more" style="font-family: monospace">
            <thead>
            <tr>
                <th>Получено</th>
                <th>Источник</th>
                <th>AHL</th>
                <th>Теги</th>
                <th>Направления</th>
            </tr>
            </thead>
            <tbody>
            <tr ng-repeat="item in records_sliced()">
                <td><a href="#" ng-click="open_message(item.uid)">[[ aux.moment(item.uid * 1000 / 4096).format('YYYY.MM.DD HH:mm:ss') ]]</a></td>
                <td><a href="#" ng-click="add_flt_origin(item.o)">[[ item.o ]]</a></td>
                <td>[[ item.ahl ]]</td>
                <td><a href="#" ng-click="add_flt_tag(tag)" ng-repeat="tag in item.t" class="tag-link">[[ tag ]]</a></td>
                <td><a href="#" ng-click="add_flt_dest(dest)" ng-repeat="dest in item.d" class="tag-link">[[ dest ]]</a></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
<script type="text/ng-template" id="_core.message.html">{% include '_core.message.html' %}</script>
<script>{% include '_core.message.js' %}</script>
<script>
    Ametist.controller('MessageSelectCtrl', ['$scope', '$http', '$modal', function ($scope, $http, $modal) {
        $scope.aux = aux;
        $scope._loading = false;
        $scope.conditions_visible = false;
        $scope.search_date = new Date();
        $scope.search_date.setMinutes(0);
        $scope.records = [];
        $scope.flt_tags = [];
        $scope.flt_origins = [];
        $scope.flt_dests = [];
        $scope.current_page = 1;
        $scope.items_per_page = 20;
        $scope.max_date = new Date();

        $scope.toggle_conditions_visible = function () {
            $scope.conditions_visible = !$scope.conditions_visible;
            $scope.max_date = new Date();
        };

        $scope.records_filtered = function () {
            var flt_tags = $scope.flt_tags;
            var flt_dests = $scope.flt_dests;
            var flt_origins = $scope.flt_origins;
            var retval = $scope.records.filter(function (item) {
                return (aux.allin(flt_tags, item.t) || !flt_tags.length) &&
                        (aux.allin(flt_dests, item.d) || !flt_dests.length) &&
                        ((flt_origins.indexOf(item.o) !== -1) || !flt_origins.length)
            });
            return retval;
        };
        $scope.records_sliced = function () {
            var retval = $scope.records_filtered().slice(
                ($scope.current_page - 1) * $scope.items_per_page,
                $scope.current_page * $scope.items_per_page
            );
            return retval;
        };
        $scope.add_flt_origin = function (origin) {
            if ($scope.flt_origins.indexOf(origin) === -1) {
                $scope.flt_origins.push(origin)
            }
        };
        $scope.add_flt_dest = function (dest) {
            if ($scope.flt_dests.indexOf(dest) === -1) {
                $scope.flt_dests.push(dest)
            }
        };
        $scope.add_flt_tag = function (tag) {
            if ($scope.flt_tags.indexOf(tag) === -1) {
                $scope.flt_tags.push(tag)
            }
        };
        $http.get('{{ url_for('CoreControl.api_ioj_minimum') }}').success(function (data) {
            $scope.min_date = new Date(data.result * 1000);
        });
        $scope.get_data = function () {
            $scope._loading = true;
            $scope.conditions_visible = false;
            $http.get('{{ url_for('CoreControl.api_ioj_thedate') }}' + moment($scope.search_date).utc().format('YYYYMMDDHHmm'))
                    .success(function (data) {
                        $scope.records = data.result;
                        $scope._loading = false;
                    })
                    .error(function () {
                        $scope._loading = false;
                    })
        };
        $scope.open_message = function (uid) {
            $http.get('{{ url_for('CoreControl.api_ioj_uid') }}' + uid).success(function (data) {
                var instance = $modal.open({
                    templateUrl: '_core.message.html',
                    controller: CoreMessageModal,
                    resolve: {
                        message: function () {
                            return {
                                text: data,
                                uid: uid
                            }
                        }
                    }
                });
            })
        }
    }])
</script>

www/templates/_core.message.html
<div class="modal-header">
    <button type="button" class="close" ng-click="close()">&times;</button>
    <h4>Сообщение: [[ message.uid ]]</h4>
</div>
<div class="modal-body">
    <span ng-bind-html="message.text" style="font-family: monospace"></span>
</div>
<div class="modal-footer">
    <button class="btn btn-primary" ng-click="close()">Закрыть</button>
</div>

www/templates/_core.rep.html
    <div ng-controller="CoreXRepCtrl">
        <div class="panel panel-primary">
            <div class="panel-heading">Условия выборки</div>
            <table class="table">
                <tbody>
                <tr>
                    <td class="col-md-2"><label for="origin">Канал ввода:</label></td>
                    <td class="col-md-10"><input id="origin" type="text" class="form-control"
                                                 ng-model="model.inputs"></td>
                </tr>
                <tr>
                    <td><label for="ahl">AHL:</label></td>
                    <td><input id="ahl" type="text" class="form-control" ng-model="model.ahl"></td>
                </tr>
                <tr>
                    <td><label for="tags_m" for="tags_p">Тэги:</label></td>
                    <td>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon glyphicon glyphicon-plus"></span>
                                    <input id="tags_p" type="text" class="form-control"
                                           ng-model="model.tags_p">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon glyphicon glyphicon-minus"></span>
                                    <input id="tags_m" type="text" class="form-control"
                                           ng-model="model.tags_m">
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td><label for="dests_m" for="dests_p">Направления:</label></td>
                    <td>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon glyphicon glyphicon-plus"></span>
                                    <input id="tags_p" type="text" class="form-control"
                                           ng-model="model.dests_p">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="input-group">
                                    <span class="input-group-addon glyphicon glyphicon-minus"></span>
                                    <input id="tags_m" type="text" class="form-control"
                                           ng-model="model.dests_m">
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="panel panel-primary">
            <div class="panel-heading">Действия</div>
            <table class="table">
                <tbody>
                <tr>
                    <td class="col-md-2"><label for="direct">Направить в:</label></td>
                    <td class="col-md-10">
                        {% for channel_name in channels %}
                            <div class="form-group">
                                <input type="checkbox" id="to_{{ channel_name }}"
                                       ng-model="model.dests.{{ channel_name }}">
                                <label for="to_{{ channel_name }}">{{ channel_name }}</label>
                            </div>
                        {% endfor %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="col-md-2 col-md-offset-10">
                <button class="btn btn-success btn-block" ng-click="post_inject()">
                    Go!
                </button>
            </div>
        </div>
    </div>
<script>
    Ametist.controller('CoreXRepCtrl', ['$scope', '$http', function ($scope, $http) {
        $scope.aux = aux;
        $scope.stats = null;
        $scope.model = {
            dests: {}
        };
        $scope.post_inject = function () {
            $http.post('{{ url_for('CoreControl.api_inject') }}', $scope.model);
        }
    }])
</script>

www/templates/_send.index.html
<div id="SendMessagePanel" class="panel panel-primary" ng-controller="SendCtrl">
    <div class="panel-heading">
        Отправить сообщение
    </div>
    <div class="panel-body">
        <form class="form form-horizontal">
            <fieldset class="row">
                <div class="control-group col-sm-4">
                    <label for="address" class="control-label">Адресат ГМС</label>
                    <input id="address" class="form-control" type="text" ng-model="chosen_template.hms_addr">
                </div>
                <div class="control-group col-sm-8">
                    <label for="send" class="control-label">Шаблоны:</label>
                    <select class="form-control" ng-model="dummy" ng-change="template_changed()" ng-options="opt.name for opt in templates"></select>
                </div>
            </fieldset>
            <fieldset class="row">
                <div class="control-group col-sm-5">
                    <label for="TTiiAA" class="control-label">AHL</label>
                    <input id="TTiiAA" class="form-control" type="text" ng-model="chosen_template.ahl">
                </div>
                <div class="control-group col-sm-4">
                    <label for="Timestamp" class="control-label">Время</label>
                    <input id="Timestamp" class="form-control" type="text" ng-model="chosen_template.timestamp">
                </div>
                <div class="control-group col-sm-3">
                    <label for="Group" class="control-label">Группа</label>
                    <input id="Group" class="form-control" type="text" ng-model="chosen_template.group">
                </div>
            </fieldset>
            <fieldset class="row marginal">
                <div class="control-group col-md-12">
                    <label for="Text" class="control-label">Текст</label>
                    <textarea id="Text" class="form-control" rows="20"
                              ng-model="chosen_template.text"></textarea>
                </div>
            </fieldset>
            <div class="row">
                <div class="col-md-4 col-md-offset-8">
                    <div class="btn-group pull-right">
                        <button id="send" class="btn btn-success" ng-click="send_message()">Отправить</button>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="" ng-click="save_template()">Сохранить шаблон...</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    SaveTemplateCtrl = function ($scope, $modalInstance, templateData) {
        $scope.template = templateData;
        $scope.name = '';
        $scope.accept = function () {
            $modalInstance.close(this.name);
        };
        $scope.cancel = function () {
            $modalInstance.dismiss('cancel');
        };
    };
    Ametist.controller('SendCtrl', ['$scope', '$http', '$modal', function SendCtrl($scope, $http, $modal) {
        {#$scope.group = {{ group | tojson }};#}
        $scope.dummy = {};
        $scope.templates = [];
        $scope.chosen_template = null;
        $scope.template_changed = function (item) {
            item = $scope.dummy;
            $scope.chosen_template = angular.extend({}, item.data);
            $scope.chosen_template.timestamp = moment().format('DDHHmm');
        };
        $http.get('{{ url_for('Send.api_templates') }}')
                .success(function (data) {
                    $scope.templates = data.result;
                });
        $scope.send_message = function () {
            $('#SendMessagePanel *').attr('disabled', true);
            $http.post('{{ url_for('Send.api_send_wmo_message') }}', $scope.chosen_template)
                    .then(function () {
                        $('#SendMessagePanel *').attr('disabled', false);
                    })
        };
        $scope.save_template = function () {
            var modalInstance = $modal.open({
                templateUrl: 'save_template.html',
                controller: SaveTemplateCtrl,
                resolve: {
                    templateData: function () {
                        return $scope.chosen_template;
                    }
                }
            });
            modalInstance.result.then(function (name) {
                $http.post('{{ url_for('Send.api_save_wmo_template') }}', {
                    name: name,
                    data: {
                        ahl: $scope.chosen_template.ahl,
                        group: $scope.chosen_template.group,
                        hms_addr: $scope.chosen_template.hms_addr,
                        text: $scope.chosen_template.text
                    }
                }).success(function (data) {
                    $scope.templates = data.result;
                })
            })
        }
    }])
</script>

www/templates/index.html
{% extends '_base.html' %}